version: "2"
services:
  consul:
    command: agent -dev -client 0.0.0.0
    image: consul:latest
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  api:
    command: --registry_address=consul:8500 --enable_stats --register_interval=5 --register_ttl=10 api
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
    - "8080:8080"
  sidecar:
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 sidecar
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
    - "8081:8081"
  web:
    command: --registry_address=consul:8500 --register_interval=5 --register_ttl=10 web
    image: microhq/micro:latest
    depends_on:
      - consul
    ports:
    - "8082:8082"
